### ISSUE TITLE
Configure logger via ENV vars

### ISSUE THREAD

**Issue by CptOfEvilMinions** [jmpsec/osctrl#209]
docker-compose:
```
osctrl-admin:
    container_name: 'osctrl-admin'
    restart: unless-stopped
    image: osctrl-admin:v${OSCTRL_VERSION}
    environment:
      #### TLS settings ####
      - TLS_SERVER=false
      - SERVICE_CONFIG=false
      - SERVICE_LISTENER=0.0.0.0
      - SERVICE_PORT=9001
      - SERVICE_HOST=0.0.0.0
      - SERVICE_AUTH=none
      #### Logging ####
      - SERVICE_LOGGER=none
 ```

Docker log:
```
osctrl-admin    | main.go:480: Initialize carves
osctrl-admin    | main.go:482: Initialize sessions
osctrl-admin    | main.go:484: Loading service settings
osctrl-admin    | settings.go:392: SetString 0.0.0.0 admin json_listener
osctrl-admin    | settings.go:392: SetString 9001 admin json_port
osctrl-admin    | settings.go:392: SetString 0.0.0.0 admin json_host
osctrl-admin    | settings.go:392: SetString none admin json_auth
osctrl-admin    | settings.go:392: SetString db admin json_logging
osctrl-admin    | main.go:488: Loading service metrics
osctrl-admin    | main.go:496: Error loading logger - open config/logger.json: no such file or directory
```
