### ISSUE TITLE
Redis password should be set to `null`

### ISSUE THREAD

**Issue by CptOfEvilMinions** [jmpsec/osctrl#227]
Redis password should be set to `null` or an empty string. AWS Elasticache nor Docker Redis support the ability to set a password with ease. Osctrl assumes a password is going to be set. As seen below, I have to set `REDIS_PASS=` to connect to Redis without a password.

docker-compose:
```yaml
osctrl-api:
    container_name: 'osctrl-api'
    restart: unless-stopped
    image: osctrl-api:v${OSCTRL_VERSION}
    environment:
      ....
      #### Redis settings ####
      - REDIS_CONFIG=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
```

**Comment by javuto** [comment]
Do you want me to skip the password if it is set to empty string?

**Comment by CptOfEvilMinions** [comment]
Correct, if `REDIS_PASS` is not set then just assume there is no password.

**Comment by CptOfEvilMinions** [comment]
docker-compose:
```yaml
 osctrl-tls:
    container_name: 'osctrl-api'
    restart: unless-stopped
    image: jmpsec/osctrl-tls:v${OSCTRL_VERSION}
    environment:
     ...
      #### Redis settings ####
      - REDIS_CONFIG=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
```

log output:
```
osctrl-tls             | main.go:381: Connection to backend successful!
osctrl-tls             | main.go:390: Initializing cache...
osctrl-tls             | main.go:393: Failed to connect to redis - ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
osctrl-tls exited with code 1
```
